---
function:
  handler: ${self:custom.alias}/src/bill_of_lading.handler
  name: ${self:service}-bill-of-lading-${self:provider.stage}
  description: bill of lading api service - ${self:provider.stage}
  warmup:
    default:
      enabled: true
      alias: ${self:custom.alias}
  events:
    - http:
        path: /billoflading
        method: GET
        cors: true
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            400:
              pattern: '.*httpStatus\": 400.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
    - ${self:custom.alias}/src/bill_of_lading.py
    - src/common.py
  environment:
    billOfLading_key: ${ssm:/omni-dw/${self:provider.stage}/bol/API_KEY~true}
    URL: ${ssm:/omni-dw/${self:provider.stage}/billOfLading/wt/url}