---
function:
  handler: src/createShipment.handler
  name: ${self:service}-create-shipment-${self:provider.stage}
  description: create shipment api service - ${self:provider.stage}
  events:
    - http:
        path: /create/shipment
        method: POST
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            400:
              pattern: '.*httpStatus\": 400.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
    - src/createShipment.py
    - src/common.py
    - psycopg2/*
  environment:
    CUSTOMER_ENTITLEMENT_TABLE: ${ssm:/${self:service}/${self:provider.stage}/customerEntitlement/table}
    ACCOUNT_INFO_TABLE: ${ssm:/${self:service}/${self:provider.stage}/accountInfo/table}
    SHIPMENT_DETAILS_TABLE: ${ssm:/${self:service}/${self:provider.stage}/shipmentDetails/table}
    CUSTOMER_ENTITLEMENT_TABLE_INDEX: ${ssm:/${self:service}/${self:provider.stage}/entitlement/houseBillNumber/index}
    ACCOUNT_INFO_TABLE_INDEX: ${ssm:/${self:service}/${self:provider.stage}/accountInfo/customerId/index}
    REGION: ${self:provider.region}
    URL: ${ssm:/${self:service}/${self:provider.stage}/createShipment/wt/url}
    wt_soap_username: ${ssm:/${self:service}/${self:provider.stage}/wt/soap/username~true}
    wt_soap_password: ${ssm:/${self:service}/${self:provider.stage}/wt/soap/password~true}
    db_username: ${ssm:/${self:service}/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/${self:service}/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/${self:service}/${self:provider.stage}/db/name}
    db_host: ${ssm:/${self:service}/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/${self:service}/${self:provider.stage}/db/port} 
