---
function:
  handler: src/customerEntitlementSync.handler
  name: ${self:service}-customer-entitlement-sync-${self:provider.stage}
  description: customer entitlement sync - ${self:provider.stage}
  events: 
    - s3:
        bucket: ${ssm:/${self:service}/${self:provider.stage}/s3/datapipeline/bucket}
        event: s3:ObjectCreated:*
        rules:
          - prefix: Data/
        existing: true
  package:
    include:
    - src/customerEntitlementSync.py
  environment:
    tableName: ${ssm:/${self:service}/${self:provider.stage}/customerEntitlement/table}
    bucket: ${ssm:/${self:service}/${self:provider.stage}/s3/datapipeline/bucket}
    s3_key: ${ssm:/${self:service}/${self:provider.stage}/entitlement/table/sync/s3/key}