---
function:
  handler: ${self:custom.alias}/src/custom_authorizer.handler
  name: ${self:service}-custom-authorizer-${self:provider.stage}
  description: custom authorizer - ${self:provider.stage}
  
  package:
    include:
    - ${self:custom.alias}/src/custom_authorizer.py
    - src/common.py
  environment:
    TOKEN_VALIDATION_TABLE: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    CUSTOMER_ENTITLEMENT_TABLE: ${ssm:/omni-dw/${self:provider.stage}/customerEntitlement/table} 
    CUSTOMER_ENTITLEMENT_HOUSEBILL_INDEX: ${ssm:/omni-dw/${self:provider.stage}/entitlement/houseBillNumber/index}
    CUSTOMER_ENTITLEMENT_FILENUMBER_INDEX: ${ssm:/omni-dw/${self:provider.stage}/entitlement/fileNumber/index}
    MANUAL_APIKEYS: ${ssm:/omni-dw-api-sevices/${self:provider.stage}/getDocument/apiKeys}
    TOKEN_VALIDATION_TABLE_INDEX: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/apiKey/index}
    ALLOWED_CUSTOMER_IDS: ${ssm:/omni-dw/allowedCustomerIds}
    REGION: ${self:provider.region}
