---
function:
  handler: ${self:custom.alias}/src/customerEntitlementSync.handler
  name: ${self:service}-customer-entitlement-sync-${self:provider.stage}
  description: customer entitlement sync - ${self:provider.stage}
  events: 
    - existingS3:
        bucket: ${ssm:/omni-dw/${self:provider.stage}/s3/datapipeline/bucket}
        events: 
          - s3:ObjectCreated:*
        rules:
          - prefix: Data/
  package:
    include:
    - ${self:custom.alias}/src/customerEntitlementSync.py
  environment:
    tableName: ${ssm:/omni-dw/${self:provider.stage}/customerEntitlement/table}
    bucket: ${ssm:/omni-dw/${self:provider.stage}/s3/datapipeline/bucket}
    s3_key: ${ssm:/omni-dw/${self:provider.stage}/entitlement/table/sync/s3/key}