---
function:
  handler: src/customerEntitlementSync.handler
  name: ${self:service}-customer-entitlement-sync-${self:provider.stage}
  description: customer entitlement sync - ${self:provider.stage}
  package:
    include:
    - src/customerEntitlementSync.py
  environment:
    tableName: ${ssm:/${self:service}/${self:provider.stage}/customerEntitlementTable}
    bucket: dw-datapipeline-dev