---
function:
  handler: v1/src/freightlabel.handler
  name: ${self:service}-freightlabel-${self:provider.stage}
  description: freightlabel api service - ${self:provider.stage}
  
  events:
    - http:
        path: /freightlabel
        method: GET
        cors: true
        integration: lambda
        private: true
        authorizer:
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '.*httpStatus\": 400.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
      - v1/src/freightlabel.py
  environment:
    label_key: ${ssm:/omni-dw/${self:provider.stage}/pod/apiKey}
    label_URL: ${ssm:/omni-dw/${self:provider.stage}/label/wt/url}
