---
function:
  handler: ${self:custom.alias}/src/get_document_alb.handler
  name: ${self:service}-get-document-alb-${self:provider.stage}
  description: get document alb api service-${self:provider.stage}
  runtime: nodejs14.x
  timeout: 60
  package:
    include:
      - ${self:custom.alias}/src/get_document_alb.js
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    TOKEN_VALIDATOR: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    GET_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/websli/api/url}
    DOCUMENTS_BUCKET: !Ref DocumentBucket
