---
function:
  handler: ${self:custom.alias}/src/get_document.handler
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetB}
  name: ${self:service}-get-document-${self:provider.stage}
  description: get document api service-${self:provider.stage}
  runtime: nodejs14.x
  timeout: 60

  events:
    # - alb:
    #     listenerArn: !Ref ALBLoadBalancer
    #     priority: 1
    #     targetGroupName: !GetAtt ALBTargetGroup.TargetGroupName
    #     conditions:
    #       path: /shipment/getdocument
    - http:
        path: /shipment/getdocument
        method: GET
        integration: lambda
        private: true
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
        authorizer:
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
  package:
    include:
      - ${self:custom.alias}/src/get_document.js
      - node_modules/**
  # layers:
  #   - !Ref DWAPILayerLambdaLayer
  # package:
  #   #individually: true
  #   patterns:
  #     - ${self:custom.alias}/src/get_document.js
  #     - "!**/*"
  environment:
    REGION: ${self:provider.region}
    TOKEN_VALIDATOR: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    TOKEN_VALIDATION_TABLE_INDEX: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/apiKey/index.allColumns}
    GET_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/websli/api/url}
    DOCUMENTS_BUCKET: !Ref DocumentBucket
