---
function:
  handler: ${self:custom.alias}/src/get_rating.handler
  name: ${self:service}-get-rating-${self:provider.stage}
  description: Rating detail api service - ${self:provider.stage}
  runtime: nodejs12.x
  events:
    - http:
        path: /ratings
        method: POST
        integration: lambda
        private: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
      - ${self:custom.alias}/src/get_rating.js
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    TOKEN_VALIDATOR: ${ssm:/omni/${self:provider.stage}/token/validator/table/name}
    RATING_API: ${ssm:/omni-dw/${self:provider.stage}/api/rating}
