---
function:
  handler: ${self:custom.alias}/src/get_document.handler
  name: ${self:service}-get-document-${self:provider.stage}
  description: get document api service-${self:provider.stage}
  runtime: nodejs12.x
  events:
    - http:
        path: /shipment/getDocument
        method: GET
        integration: lambda
        private: true
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
        authorizer:
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
  package:
    include:
      - ${self:custom.alias}/src/get_document.js
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    TOKEN_VALIDATOR: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    GETDOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/api/getdocument-websliapi}
