---
function:
  handler: ${self:custom.alias}/src/get_rating.handler
  name: ${self:service}-get-rating-${self:provider.stage}
  description: get rating api service - ${self:provider.stage}
  events:
    - http:
        path: /rating
        method: POST
        integration: lambda
        private: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            400:
              pattern: '.*httpStatus\": 400.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
    - ${self:custom.alias}/src/get_rating.py