---
function:
  handler: ${self:custom.alias}/src/get_document_alb.handler
  name: ${self:service}-get-document-alb-${self:provider.stage}
  description: get document alb api service-${self:provider.stage}
  runtime: nodejs14.x
  timeout: 60
  events:
    - alb:
        listenerArn: !Ref ALBLoadBalancer
        priority: 1
        targetGroupName: !GetAtt ALBTargetGroup.TargetGroupName
        conditions:
          path: /shipment/getdocument
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
      - ${self:custom.alias}/src/get_document_alb.js
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    TOKEN_VALIDATOR: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    GET_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/websli/api/url}
    DOCUMENTS_BUCKET: !Ref DocumentBucket
