---
function:
  handler: ${self:custom.alias}/src/get_document_alb.handler
  name: ${self:service}-get-document-alb-${self:provider.stage}
  description: get document alb api service-${self:provider.stage}
  runtime: nodejs14.x
  timeout: 180
  layers:
    - !Ref DWAPILayerLambdaLayer  
  package:
    include:
      - ${self:custom.alias}/src/get_document_alb.js
  environment:
    REGION: ${self:provider.region}
    TOKEN_VALIDATOR: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    GET_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/websli/api/url}
    DOCUMENTS_BUCKET: !Ref DocumentBucket
    TOKEN_VALIDATION_TABLE: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    TOKEN_VALIDATION_TABLE_INDEX: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/apiKey/index.allColumns}
