---
function:
  handler: src/invoiceDetailv101.handler
  name: ${self:service}-invoice-detail-v101-${self:provider.stage}
  description: invoice detail api service v101 - ${self:provider.stage}
  events: 
    - http: 
        path: /invoice/detail/v1.01
        method: GET
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer-v101
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            202:
              pattern: '.*httpStatus\": 202.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
    - src/invoiceDetailv101.py
    - src/common.py
    - psycopg2/*
  environment:
    db_username: ${ssm:/${self:service}/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/${self:service}/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/${self:service}/${self:provider.stage}/db/name}
    db_host: ${ssm:/${self:service}/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/${self:service}/${self:provider.stage}/db/port}
    REGION: ${self:provider.region}