---
function:
  handler: ${self:custom.alias}/src/invoiceDetail.handler
  name: ${self:service}-invoice-detail-${self:provider.stage}
  description: invoice detail api service - ${self:provider.stage}
  events: 
    - http: 
        path: /invoice/detail
        method: GET
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            202:
              pattern: '.*httpStatus\": 202.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
    - ${self:custom.alias}/src/invoiceDetail.py
    - src/common.py
    - psycopg2/*
  environment:
    db_username: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    db_host: ${ssm:/omni-dw/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/omni-dw/${self:provider.stage}/db/port}
    REGION: ${self:provider.region}