function:
  handler: ${self:custom.alias}/src/ltl_batch_rating.handler
  name: ${self:service}-ltl-batch-rating-${self:provider.stage}
  description: ltl batch rating api service - ${self:provider.stage}
  runtime: nodejs18.x
  timeout: 30
  layers:
    - !Ref DWAPILayerLambdaLayer
  memorySize: 512
  package:
    include:
      - ${self:custom.alias}/src/ltl_batch_rating.js
      - src/shared/**
  events:
    - http:
        path: /shipment/ltlrate/batch
        method: POST
        integration: lambda
        private: true
        cors: true
        request:
            contentHandling: CONVERT_TO_BINARY
            parser: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
            passThrough: WHEN_NO_MATCH
            # schemas:
            #   application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: ${file(xlsx_format.vtl)}
