---
function:
  handler: ${self:custom.alias}/src/shipment_list.handler
  name: ${self:service}-shipment-list-${self:provider.stage}
  description: shipment list api service - ${self:provider.stage}
  runtime: nodejs14.x
  timeout: 500
  events:
    - http:
        path: /shipment/list/{customerID}
        method: GET
        cors: true
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            400:
              pattern: '.*httpStatus\": 400.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
    - ${self:custom.alias}/src/list_shipment.js
    - src/shared/**
  environment:
    CUSTOMER_ENTITLEMENT_TABLE: ${ssm:/omni-dw/${self:provider.stage}/customerEntitlement/table}
    TOKEN_VALIDATION_TABLE: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    REGION: ${self:provider.region}
