function:
  handler: ${self:custom.alias}/src/shipment_details_collector.handler
  name: ${self:service}-shipment-details-collector-${self:provider.stage}
  description: shipment details collector api service - ${self:provider.stage}
  runtime: nodejs18.x
  timeout: 300
  layers:
    - !Ref DWAPILayerLambdaLayer
  memorySize: 512

  package:
    include:
      - ${self:custom.alias}/src/shipment_details_collector.js
  events:
    - stream: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.streamArn~true}
    - stream: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-milestone/ddb.streamArn~true}
    - stream: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/consignee/ddb.streamArn~true}
    - stream: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipper/ddb.streamArn~true}
    - stream: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/references/ddb.streamArn~true}
    - stream: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-desc/ddb.streamArn~true}