---
function:
  handler: ${self:custom.alias}/src/shipment-header-table-stream-processor.handler
  name: ${self:service}-shipment-header-table-stream-processor-${self:provider.stage}
  description: process and filters shipment header table stream - ${self:provider.stage}
  runtime: nodejs14.x
  timeout: 500
  events:
    - stream: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.streamArn~true}

  package:
    include:
      - ${self:custom.alias}/src/shipment-header-table-stream-processor.js
      - src/shared/**
      - node_modules/**
  environment:
    SHIPMENT_HEADER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName~true}
    REGION: ${self:provider.region}
    SHIPMENT_HEADER_TABLE_STREAM_QUEUE: !Ref ShipmentFileTableStreamQueue
