---
function:
  handler: ${self:custom.alias}/src/add_document.handler
  name: ${self:service}-add-document-${self:provider.stage}
  description: add document api service - ${self:provider.stage
  runtime: nodejs14.x
  timeout: 500
  memorySize: 2048
  events:
    - http:
        path: /shipment/addDocument
        method: POST
        integration: lambda
        private: true
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
        authorizer:
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
  # package:
  #   include:
  #     - ${self:custom.alias}/src/add_document.js
  #     - node_modules/**
  layers:
    - !Ref DWAPILayerLambdaLayer
  package:
    #individually: true
    patterns:
      - ${self:custom.alias}/src/add_document.js
      - "!**/*"
  environment:
    REGION: ${self:provider.region}
    UPLOAD_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/api/addDocument}
    HOUSEBILL_TABLE: ${ssm:/omni-dw/${self:provider.stage}/customerEntitlement/table}
    ADD_DOCUMENT_LOG_TABLE: ${ssm:/omni-dw/${self:provider.stage}/addDocumentLog/table~true}
    HOUSEBILL_TABLE_INDEX: ${ssm:/omni-dw/${self:provider.stage}/entitlement/houseBillNumber/index}
    FILENUMBER_TABLE_INDEX: ${ssm:/omni-dw/${self:provider.stage}/entitlement/fileNumber/index}
    IVIA_CUSTOMER_ID: ${ssm:/omni-dw/${self:provider.stage}/api/iviaId}
    IVIA_VENDOR_ID: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/ivia/shipmentApar/filterVendorId~true} #"T19262"

    SHIPMENT_HEADER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName~true}
    ADDRESS_MAPPING_TABLE: ${ssm:/omni-ivia/${self:provider.stage}/address-mapping/ddb.tableName}
    SHIPMENT_APAR_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-apar/ddb.tableName~true}
