---
function:
  handler: ${self:custom.alias}/src/get_rate.handler
  name: ${self:service}-shipment-rate-${self:provider.stage}
  description: Rating detail api service - ${self:provider.stage}
  warmup:
    default:
      enabled: true
      alias: ${self:custom.alias}
  runtime: nodejs16.x
  logSubscription: true
  timeout: 90
  events:
    - http:
        path: /shipment/rate
        method: POST
        integration: lambda
        private: true
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
        authorizer:
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
  # layers:
  #   - !Ref DWAPILayerLambdaLayer
  # package:
  #   #individually: true
  #   patterns:
  #     - ${self:custom.alias}/src/get_rate.js
  #     - src/shared/logger.js
  #     - "!**/*"
  package:
    include:
      - ${self:custom.alias}/src/get_rate.js
      - src/shared/logger.js
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    RATING_API: ${ssm:/omni-dw/${self:provider.stage}/api/rate}
    ACCOUNT_INFO_TABLE: ${ssm:/omni-dw/${self:provider.stage}/accountInfo/table}
    ACCOUNT_INFO_TABLE_INDEX: ${ssm:/omni-dw/${self:provider.stage}/accountInfo/customerId/index}
    TOKEN_VALIDATOR_TABLE: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    FUNCTION_NAME: ${self:service}-shipment-rate-${self:provider.stage}
    SERVICE_NAME: ${self:service}
    APPLICATION: DataWarehouse
