---
function:
  handler: ${self:custom.alias}/src/shipment_detail.handler
  name: ${self:service}-shipment-detail-${self:provider.stage}
  description: shipment detail api service - ${self:provider.stage}
  
  events: 
    - http: 
        path: /shipment/detail
        method: GET
        cors: true
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
    - v101/src/shipment_detail.py
    - ${self:custom.alias}/src/shipment_detail.py
    - src/common.py
    - psycopg2/*
  environment:
    db_username: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    db_host: ${ssm:/omni-dw/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/omni-dw/${self:provider.stage}/db/port} 
    SHIPMENT_DETAILS_TABLE: ${ssm:/omni-dw/${self:provider.stage}/shipmentDetails/table}
    SHIPMENT_DETAILS_HOUSEBILL_INDEX: ${ssm:/omni-dw/${self:provider.stage}/shipmentDetails/houseBillKey/index}
    SHIPMENT_DETAILS_FILENUMBER_INDEX: ${ssm:/omni-dw/${self:provider.stage}/shipmentDetails/FileNumber/index}
    REGION: ${self:provider.region}
