---
function:
  handler: ${self:custom.alias}/src/add_document.handler
  name: ${self:service}-add-document-${self:provider.stage}
  description: add document api service - ${self:provider.stage}
  
  runtime: nodejs14.x
  timeout: 500
  memorySize: 2048
  events:
    - http:
        path: /shipment/addDocument
        method: POST
        integration: lambda
        private: true
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
        # authorizer:
        #   name: custom-authorizer
        #   resultTtlInSeconds: 0
        #   identitySource: method.request.header.x-api-key
        #   type: request
  package:
    include:
      - v2/src/add_document.js
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    ULOAD_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/api/addDocument}