---
function:
  handler: src/shipmentInfov101.handler
  name: ${self:service}-shipment-info-v101-${self:provider.stage}
  description: shipment info api service v101- ${self:provider.stage}
  events: 
    - http:  
        path: /v1.01/shipment/info
        method: GET
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer-v101
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
    - src/shipmentInfov101.py
    - src/common.py
    - psycopg2/*
  environment:
    db_username: ${ssm:/${self:service}/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/${self:service}/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/${self:service}/${self:provider.stage}/db/name}
    db_host: ${ssm:/${self:service}/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/${self:service}/${self:provider.stage}/db/port} 
    SHIPMENT_DETAILS_TABLE: ${ssm:/${self:service}/${self:provider.stage}/shipmentDetails/table}
    SHIPMENT_DETAILS_HOUSEBILL_INDEX: ${ssm:/${self:service}/${self:provider.stage}/shipmentDetails/houseBillKey/index}
    SHIPMENT_DETAILS_FILENUMBER_INDEX: ${ssm:/${self:service}/${self:provider.stage}/shipmentDetails/FileNumber/index}
    REGION: ${self:provider.region}
