function:
  handler: ${self:custom.alias}/src/add_milestone.handler
  name: ${self:service}-add-milestone-${self:provider.stage}
  description: add milestone api service - ${self:provider.stage}
  runtime: nodejs14.x
  timeout: 60
  memorySize: 512
  environment:
    ADD_MILESTONE_URL: ${ssm:/omni-ivia/${self:provider.stage}/addMilestone/url}
  package:
    include:
      - ${self:custom.alias}/src/add_milestone.js
      - node_modules/**
  events:
    - http:
        path: /shipment/addmilestone
        method: POST
        integration: lambda
        private: true
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
        authorizer:
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
