---
function:
  handler: ${self:custom.alias}/src/shippeo_pod_upload_doc.handler
  name: ${self:service}-shippeo-pod-upload-doc-${self:provider.stage}
  description: shippeo upload pod doc - ${self:provider.stage}
  runtime: nodejs18.x
  timeout: 500
  layers:
    - { Ref: DWAPILayerLambdaLayer }
  events:
    - sqs:
        arn: !GetAtt ShipmentFileTableStreamQueue.Arn
        batchSize:
          1
          # Fn::GetAtt:
          #   - ShipmentFileTableStreamQueue
          #   - Arn

  package:
    include:
      - v201/src/shippeo_pod_upload_doc.js
      # - src/shared/**
      - node_modules/**
  environment:
    SHIPMENT_HEADER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName~true}
    SHIPMENT_FILE_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-file/ddb.tableName~true}
    SHIPMENT_HEADER_TABLE_BILL_NO_INDEX: ${ssm:/omni-dw/${self:provider.stage}/shipment-header-index/ddb.BillNoIndex}
    REGION: ${self:provider.region}
    LOG_TABLE: !Ref UploadedDocLogTable
  role: ShippeoPODRole
