---
function:
  handler: ${self:custom.alias}/src/get_rate.handler
  name: ${self:service}-shipment-rate-${self:provider.stage}
  description: Rating detail api service - ${self:provider.stage}
  warmup:
    default:
      enabled: true
      alias: ${self:custom.alias}
  runtime: nodejs12.x
  events:
    - http:
        path: /shipment/rate
        method: POST
        integration: lambda
        private: true
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
        authorizer:
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
  package:
    include:
      - ${self:custom.alias}/src/get_rate.js
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    RATING_API: ${ssm:/omni-dw/${self:provider.stage}/api/rate}
    ACCOUNT_INFO_TABLE: ${ssm:/omni-dw/${self:provider.stage}/accountInfo/table}
    ACCOUNT_INFO_TABLE_INDEX: ${ssm:/omni-dw/${self:provider.stage}/accountInfo/customerId/index}

custom:
  logSubscription:
    enabled: true
    destinationArn: arn:aws:logs:${self:provider.region}:332753493246:destination:bce-logs-cw-destination-${self:provider.region}-${self:provider.stage}
    filterPattern: '{$.service-name = "*"}'
    
plugins:
 - serverless-plugin-log-subscription