---
function:
  handler: v1/src/uloadpoddocument.handler
  name: ${self:service}-uload-pod-document-${self:provider.stage}
  description: uload pod document api service - ${self:provider.stage}
  runtime: nodejs12.x
  events:
    - http:
        path: /uloadpoddocument
        method: POST
        integration: lambda
        private: true
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
        authorizer:
          name: custom-authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
  package:
    include:
      - v1/src/uloadpoddocument.js
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    ULOAD_POD_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/api/uloadpoddocument}
