---
function:
  handler: ${self:custom.alias}/src/wd_api.handler
  name: ${self:service}-wd-${self:provider.stage}
  description: WD api service - ${self:provider.stage}
  runtime: nodejs12.x
  events:
    - schedule:
        name: wd lambda event-${self:provider.stage}
        description: Schedule event for every 30 minutes to invoke the wd lambda
        rate: rate(30 minutes)
    - http:
        path: /wd
        method: POST
        integration: lambda
        private: true
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
      - ${self:custom.alias}/src/wd_api.js
      - Helpers/**
      - node_modules/**
  environment:
    REGION: ${self:provider.region}
    WD_API: ${ssm:/omni-dw/${self:provider.stage}/api/wd}
    WD_API_USERNAME: ${ssm:/omni-dw/${self:provider.stage}/api/wd/username}
    WD_API_PASSWORD: ${ssm:/omni-dw/${self:provider.stage}/api/wd/password}
    WD_SHIPMENT_STATUS_TABLE: ${ssm:/omni-dw/${self:provider.stage}/wdShipmentStatus/table}
    WD_DBNAME: ${ssm:/omni-dw/${self:provider.stage}/wd/db/name}
    USER: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    HOST_URL: ${ssm:/omni-dw/${self:provider.stage}/db/host/url~true}
    PASS: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}
    PORT: ${ssm:/omni-dw/${self:provider.stage}/db/port}
