---
stateMachine:
  name: ${self:service}-netsuite-customer-state-machine-${self:provider.stage}
  definition:
    Comment: "State machine to update netsuit customer internal details"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-netsuite-customer-${self:provider.stage}"
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
      SuccessState:
        Type: Succeed
  events:
    - schedule:
        name: ${self:service}-netsuite-customer-${self:provider.stage}
        description: "schedule cloud watch event at 9PM every day for customers state machine"
        rate: cron(0 21 * * *)
