---
stateMachine:
  name: ${self:service}-netsuite-ar-state-machine-${self:provider.stage}
  crawl:
    events:
      - schedule: cron(30 22 * * *)
    definition:
      Comment: "State machine to create netsuit invoice"
      StartAt: PublishEvents
      States:
        PublishEvents:
          Type: Task
          Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-netsuite-ar-${self:provider.stage}"
          Next: EndChoice
        EndChoice:
          Type: Choice
          Choices:
            - Variable: $.hasMoreData
              StringEquals: "false"
              Next: SuccessState
            - Variable: $.hasMoreData
              StringEquals: "true"
              Next: PublishEvents
        SuccessState:
          Type: Succeed
