service: java-lambda-for-amazon-pod

layers:
  JAVA:
    path: lambdaLayer
    name: java-lambda-layer
    description: java lambda layer
    compatibleRuntimes:
      - java11
    retain: false

provider:
  name: aws
  runtime: java11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:*
    - Effect: Allow
      Action:
        - logs:*
      Resource: "*"
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}

package:
  artifact: target/hello-dev.jar

functions:
  upload-doc:
    name: ${self:service}-upload-doc-${self:provider.stage}
    handler: com.serverless.Handler
    layers:
      - !Ref JAVALambdaLayer
    package:
      patterns:
        - src/**
        - "!*/**"
